import { Metadata } from "next"
import { ErrorWrapper } from "./error-wrapper"

export const metadata: Metadata = {
  // title: 'Next.js', // simple string 
  title: {
    default: "Next js tutorial by techysanoj", // used when any children route do not write there metadata
    template: "%s | techysanoj", // to add prefix or suffix for consisten title
    absolute: "", // to break the template pattern for the parent blog
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={
          {backgroundColor: "lightblue",
          padding: "1rem,"
        }}>
          Header
        </header>
        <ErrorWrapper > {children} </ErrorWrapper>
  
        <footer style={{
          backgroundColor: "ghostwhite",
          padding: "1rem",
        }}>
          Footer
        </footer>
      </body> 
    </html>
  )
}
